services:
  - type: web
    name: glucoinsight-web
    env: node
    buildCommand: |
      apt-get update && apt-get install -y python3 python3-pip &&
      pip3 install --upgrade pip &&
      pip3 install -r requirements.txt &&
      npm ci &&
      npm run build:css
    startCommand: bash start.sh
    envVars:
      - key: EMAIL_USER
        sync: false
      - key: EMAIL_PASS
        sync: false
      - key: MONGO_URI
        sync: false
